### ISSUE TITLE
Steam login

### ISSUE THREAD

**Issue by paulyluca** [seanwlk/warface-crate-manager#11]
Hello,

The new version is not remembering the login credentials, like the previous did.

Also, Bitdefender was reporting the executable has a virus. I whitelisted it, of course... :).

Thank you for your great work.

Paul

**Comment by seanwlk** [comment]
Hi, i ran some test and works on my end. I can only assume that it's because i reworked the structure of creds.json (you still have old one) and didnt take in account that the key "auth_token" was already in use. Try deleting creds.json and logging in with the new version. 

PS:
What 2 Factor do you have ? steamguard or mail ?

**Comment by seanwlk** [comment]
> Also, Bitdefender was reporting the executable has a virus. I whitelisted it, of course... :).

Ye, nothing i can do about this. It's because of the packaging system with Pyinstaller. You could run the project directly with python source code instead if you dont want to deal with antiviruses.

**Comment by paulyluca** [comment]
> Hi, i ran some test and works on my end. I can only assume that it's because i reworked the structure of creds.json (you still have old one) and didnt take in account that the key "auth_token" was already in use. Try deleting creds.json and logging in with the new version.
> 
> PS:
> What 2 Factor do you have ? steamguard or mail ?

Hy,

Steamguard on my phone. 

I tried deleting the creds.json and logg in again. It is still not remembering the credentials. Happens on both, my PC and my laptop.

**Comment by seanwlk** [comment]
Ok, i see the problem, i messed up during testing phase. Was using an already generated creds.json file. I will push a fix now, meanwhile you can go to Releases: https://github.com/seanwlk/warface-crate-manager/releases
I updated the executable files with the patch, Can you download again and try please? Sorry for the incovenience.

**Comment by harmdhast** [comment]
@seanwlk you should consider saving creds.json in appdata and hashing it's contents especially tokens. You can go as far as hasing them with win session creds but it will require admin rights

**Comment by seanwlk** [comment]
I actually wanted to obfuscate the file but left it for future update

**Comment by paulyluca** [comment]
It is OK now.

Thank you.

**Comment by seanwlk** [comment]
Pushed https://github.com/seanwlk/warface-crate-manager/commit/6f321f494ef791cd2451e0aa65d5010416fcd8f3
