### ISSUE TITLE
Can You Make Automatically Base Research Works When is Available Energy 

### ISSUE THREAD

**Issue by Tharumax** [seanwlk/warface-crate-manager#4]
Can You Make Automatically Base Research Works When is Available Energy

**Comment by seanwlk** [comment]
I do not intend to do that because if you do the math, you'll see that you can send researches like once each 6/7 hours, which for a normal player would be useless. If you upgrade base you'll have at some point to use 60 energy for long missions. So even longer.

**Comment by Tharumax** [comment]
i have upgraded to level 2

**Comment by seanwlk** [comment]
> i have upgraded to level 2

That means that once you reach 0 energy, you'll be able to send 1 research each 10 hours.

**Comment by Tharumax** [comment]
ok, bro :) you're doing great work bro keep it up

**Comment by seanwlk** [comment]
Thanks.

**Comment by Tharumax** [comment]
You Welcome
