### ISSUE TITLE
Error for Starting Research

### ISSUE THREAD

**Issue by xyroot** [seanwlk/warface-crate-manager#5]
![image](https://user-images.githubusercontent.com/28510460/60378722-6217bb00-9a59-11e9-94d9-c360a35b43a8.png)
I know this is related to insufficient energy, what about if you can just implement a energy check before attempting to start a research
eg for base lv2: If it's less than 40 energy, don't bother starting short research, same with <30 energy for long research

It just seems alarming

**Comment by seanwlk** [comment]
Pushed commit that addresses the issue. Untested because i dont have enough energy (bitch takes ages to recharge :monkaS: ) should work tho.

I won't push a full release for this so i hope you run raw code and not compiled one
