### ISSUE TITLE
There is no option to authenticate with one-time password

### ISSUE THREAD

**Issue by ognivo777** [seanwlk/warface-crate-manager#8]
I can't login with google authenticator one-time passwords

**Comment by seanwlk** [comment]
I'm confused, where are you able to setup a G-Auth 2FA? Did you create the warface account with th "sign-in with Google" button?

**Comment by ognivo777** [comment]
Password and Security settings section in the mail box page. Or using direct [link](https://e.mail.ru/settings/2-step-auth?afterReload=1)

**Comment by seanwlk** [comment]
Oh i see, it's a mail.ru account. Sorry i don't offer full support for that. I have a mail.ru account setup with 2 Factor Authentification and it works if i login on the browser and then open the application, it doesnt ask for code anymore. In your case i guess the code is the actual password from what i understand on the page.
You can only revert the setting in the account in this case if you want to use my application.
